artifact_location: file:///C:/Users/paulo.rogerio/College_4/trabalho/trabalho/mlflow_runs/0
creation_time: 1744025764931
experiment_id: '0'
last_update_time: 1744025764931
lifecycle_stage: active
name: Default
